"""Internationalization — simple dictionary-based string lookup.

Each language is a flat dictionary. Use get_strings(lang) to retrieve
the appropriate dictionary for a given language code.

Supported languages: en, pt-br.
"""

EN = {
    # --- Report (writer.py) ---
    "report_title": "DevXOS Engineering Impact Report",
    "label_repository": "Repository",
    "label_analysis_window": "Analysis window",
    "label_churn_window": "Churn window",
    "unit_days": "days",
    "section_metrics_summary": "Metrics Summary",
    "table_metric": "Metric",
    "table_value": "Value",
    "metric_commits_total": "Commits (total)",
    "metric_commits_revert": "Commits (reverts)",
    "metric_revert_rate": "Revert rate",
    "metric_churn_events": "Churn events",
    "metric_churn_lines_affected": "Churn lines affected",
    "metric_files_touched": "Files touched",
    "metric_files_stabilized": "Files stabilized",
    "metric_stabilization_ratio": "Stabilization ratio",
    "disclaimer": (
        "Report generated by DevXOS v0.4b. "
        "Metrics are experimental and should be treated as hypotheses, not conclusions."
    ),
    "system_disclaimer": (
        "Engineering outcomes emerge from system dynamics, domain complexity, "
        "and organizational context. Metrics describe observable patterns and "
        "should not be interpreted as evaluation of teams or individuals."
    ),

    # --- Zone names (org reports) ---
    "zone_stable": "Stable",
    "zone_transitional": "Transitional",
    "zone_volatile": "Volatile",
    "section_repos_by_stabilization": "Repositories by Stabilization",

    # --- Intent / Behavior (writer.py / narrative.py) ---
    "section_engineering_behavior": "Engineering Behavior Overview",
    "section_stability_by_type": "Stability by Change Type",
    "table_intent": "Intent",
    "table_commits": "Commits",
    "table_percentage": "%",
    "table_lines_changed": "Lines Changed",
    "table_files_touched": "Files",
    "table_stabilization": "Stabilization",
    "table_churn_events": "Churn Events",
    "metric_intent_feature": "Feature",
    "metric_intent_fix": "Fix",
    "metric_intent_refactor": "Refactor",
    "metric_intent_config": "Config",
    "metric_intent_unknown": "Unknown",

    # --- PR Lifecycle (writer.py / narrative.py) ---
    "section_pr_lifecycle": "PR Lifecycle",
    "metric_pr_merged_count": "PRs merged",
    "metric_pr_median_time_to_merge": "Median time to merge (hours)",
    "metric_pr_median_size_files": "Median PR size (files)",
    "metric_pr_median_size_lines": "Median PR size (lines)",
    "metric_pr_review_rounds_median": "Median review rounds",
    "metric_pr_single_pass_rate": "Single-pass rate",

    # --- Systemic explanations (narrative.py) ---
    "systemic_stabilization_low": (
        "This may reflect domain complexity, evolving requirements, "
        "or subsystems under active development."
    ),
    "systemic_revert_high": (
        "This may reflect integration complexity, deployment challenges, "
        "or rapid experimentation cycles."
    ),
    "systemic_churn_high": (
        "This may reflect iterative development, evolving requirements, "
        "or areas of the system under active learning."
    ),
    "systemic_intent_dominant_feature": (
        "This may indicate an expansion phase or investment in new capabilities."
    ),
    "systemic_intent_dominant_fix": (
        "This may indicate a stabilization phase, technical debt remediation, "
        "or post-launch refinement."
    ),
    "systemic_intent_dominant_config": (
        "This may indicate investment in operational maturity or complex "
        "deployment pipelines requiring iterative tuning."
    ),
    "systemic_intent_dominant_refactor": (
        "This may indicate structural investment for long-term maintainability."
    ),
    "systemic_intent_dominant_unknown": (
        "Adopting conventional commit messages would improve classification accuracy."
    ),
    "systemic_intent_fix_churn_high": (
        "This may reflect complex problem domains where corrective work "
        "requires multiple iterations to converge."
    ),
    "systemic_intent_stabilization_gap": (
        "Different change types naturally stabilize at different rates "
        "depending on domain complexity and feedback loops."
    ),
    "systemic_pr_single_pass_low": (
        "This may reflect healthy review rigor, complex changes requiring "
        "discussion, or evolving coding standards."
    ),

    # --- Narrative (narrative.py) ---
    "section_key_findings": "Key Findings",
    "section_metric_details": "Metric Details",

    # Key findings templates
    "finding_stabilization_low": (
        "Stabilization ratio is {ratio} — "
        "{unstable_pct} of modified files were changed again within "
        "the churn window. This may indicate significant corrective effort."
    ),
    "finding_stabilization_high": (
        "Stabilization ratio is {ratio} — "
        "the majority of changes persisted without further modification. "
        "This suggests durable delivery."
    ),
    "finding_revert_high": (
        "Revert rate is {rate} "
        "({reverts} of {total} commits). "
        "This is above the {threshold} threshold and may "
        "indicate growing instability."
    ),
    "finding_revert_low": (
        "Revert rate is {rate} "
        "({reverts} of {total} commits), "
        "within a healthy range."
    ),
    "finding_churn_high": (
        "{events} files showed churn ({ratio} of "
        "files touched), affecting {lines} lines. "
        "High churn may indicate that changes are not stabilizing."
    ),
    "finding_churn_low": (
        "{events} files showed churn ({ratio} of "
        "files touched), affecting {lines} lines."
    ),
    "finding_volume": (
        "{commits} commits analyzed across "
        "{files} unique files."
    ),

    # PR findings
    "finding_pr_volume": (
        "{count} PRs merged in this period with a "
        "median time to merge of {hours} hours."
    ),
    "finding_pr_single_pass_high": (
        "{rate} of PRs were merged without any change requests "
        "(single-pass rate), suggesting efficient review cycles."
    ),
    "finding_pr_single_pass_low": (
        "Only {rate} of PRs were merged without change requests. "
        "Most PRs required at least one revision round."
    ),

    # PR metric explanations
    "explain_pr_time_to_merge_title": "Median Time to Merge",
    "explain_pr_time_to_merge_body": (
        "The median pull request took {hours} hours from open to merge, "
        "across {count} merged PRs. This measures the feedback loop speed — "
        "shorter times may indicate smoother review cycles or smaller PRs."
    ),
    "explain_pr_single_pass_title": "Single-Pass Rate",
    "explain_pr_single_pass_body": (
        "{rate} of PRs were merged without any CHANGES_REQUESTED review. "
        "The median PR went through {rounds} review rounds. "
        "A high single-pass rate may indicate that code is well-prepared before review, "
        "potentially aided by AI-assisted development."
    ),

    # Intent findings
    "finding_intent_dominant": (
        "{intent} commits dominate at {pct}, "
        "suggesting the primary engineering activity is {interpretation}."
    ),
    "finding_intent_fix_churn_high": (
        "Fix-related changes show {fix_churn} churn events, "
        "{comparison} feature churn ({feat_churn} events). "
        "This suggests corrective work is a significant source of instability."
    ),
    "finding_intent_fix_churn_low": (
        "Fix-related changes show {fix_churn} churn events, "
        "comparable to feature churn ({feat_churn} events)."
    ),
    "finding_intent_stabilization_gap": (
        "Stabilization varies by intent: {best} at {best_ratio} "
        "vs {worst} at {worst_ratio}."
    ),
    "intent_interpretation_feature": "new capability development",
    "intent_interpretation_fix": "corrective and remediation work",
    "intent_interpretation_refactor": "structural improvement",
    "intent_interpretation_config": "configuration and infrastructure",
    "intent_interpretation_unknown": "unclassified activity",

    # Intent metric explanations
    "explain_intent_distribution_title": "Engineering Behavior",
    "explain_intent_distribution_body": (
        "Commits were classified by intent: "
        "{feature} Feature, {fix} Fix, {refactor} Refactor, "
        "{config} Config, {unknown} Unknown. "
        "This breakdown reveals the dominant type of engineering activity — "
        "whether the team is building, fixing, or restructuring."
    ),
    "explain_intent_stability_title": "Stability by Intent",
    "explain_intent_stability_body": (
        "Stabilization ratio per change type: "
        "Feature {feat_ratio}, Fix {fix_ratio}, Refactor {refactor_ratio}. "
        "Comparing stability across intents reveals which types of changes "
        "produce durable outcomes and which require further iteration."
    ),

    # CLI
    "cli_reading_prs": "Fetching pull requests...",
    "cli_prs_found": "{count} merged PRs found.",
    "cli_prs_skipped": "skipped (no GitHub remote or gh CLI).",
    "cli_classifying": "Classifying commits...",
    "cli_classified": "{count} commits classified.",

    # Metric explanations
    "explain_revert_rate_title": "Revert Rate",
    "explain_revert_rate_body": (
        "{reverts} of {total} commits in this period "
        "were identified as reverts (commits that undo previous work). "
        "Revert rate is a proxy for instability — it measures how often changes "
        "need to be completely rolled back. Detection is based on commit message "
        "patterns and may not capture all manual reverts."
    ),
    "explain_churn_events_title": "Churn Events",
    "explain_churn_events_body": (
        "A churn event occurs when a file is modified multiple times within "
        "the churn window. {events} files were repeatedly modified, "
        "involving {lines} total lines changed. "
        "High churn can indicate corrective effort — code being fixed or rewritten "
        "shortly after initial delivery."
    ),
    "explain_stabilization_title": "Stabilization Ratio",
    "explain_stabilization_body": (
        "{stabilized} of {touched} files were not "
        "modified again within the churn window after their last change. "
        "This is the core signal/noise indicator: a high ratio means changes persist "
        "(delivery signal), a low ratio means changes are frequently rewritten "
        "(engineering noise)."
    ),

    # --- CLI (cli.py) ---
    "cli_description": (
        "Engineering intelligence for the AI era. "
        "Analyzes a Git repository and generates an impact report "
        "measuring delivery signal vs noise."
    ),
    "cli_help_repo": "Path to a local Git repository",
    "cli_help_days": "Lookback window in days (default: 90)",
    "cli_help_churn_days": "Churn detection window in days (default: 14)",
    "cli_help_out": "Output directory (default: out)",
    "cli_help_lang": "Report language: en, pt-br (default: en)",
    "cli_error_not_dir": "Error: '{path}' is not a valid directory.",
    "cli_error_not_git": "Error: '{path}' is not a Git repository.",
    "cli_banner_repo": "Repository",
    "cli_banner_lookback": "Lookback",
    "cli_banner_churn": "Churn window",
    "cli_banner_output": "Output dir",
    "cli_reading_commits": "Reading commit history...",
    "cli_commits_found": "{count} commits found.",
    "cli_no_commits": "No commits found in the specified window. Nothing to analyze.",
    "cli_analyzing": "Analyzing...",
    "cli_done": "done.",
    "cli_writing_report": "Writing report...",
    "cli_label_report": "Report",
    "cli_label_metrics": "Metrics",

    # --- Trend Analysis (v0.3) ---
    "cli_help_trend": "Enable trend analysis (compare recent vs baseline)",
    "cli_help_recent_days": "Recent window in days for trend analysis (default: 30)",
    "cli_trend_analyzing": "Computing trend analysis...",
    "cli_trend_done": "{recent}d vs {baseline}d trend computed.",
    "cli_trend_insufficient": "Trend skipped (only {count} commits in recent window, need ≥5).",

    "section_trend_analysis": "Trend Analysis (last {recent} days vs {baseline}-day baseline)",
    "table_baseline": "Baseline",
    "table_recent": "Recent",
    "table_delta": "Delta",
    "table_signal": "Signal",

    "trend_signal_stable": "— Stable",
    "trend_signal_notable_up": "▲ Notable",
    "trend_signal_notable_down": "▼ Notable",
    "trend_signal_significant_up": "▲ Significant",
    "trend_signal_significant_down": "▼ Significant",

    "trend_label_stabilization": "Stabilization",
    "trend_label_churn_rate": "Churn rate",
    "trend_label_revert_rate": "Revert rate",
    "trend_label_feature_share": "Feature share",
    "trend_label_fix_share": "Fix share",
    "trend_label_config_share": "Config share",
    "trend_label_feature_stabilization": "Feature stabilization",
    "trend_label_fix_stabilization": "Fix stabilization",
    "trend_label_pr_time_to_merge": "PR time to merge",
    "trend_label_pr_single_pass": "PR single-pass rate",

    "trend_finding_stabilization_down": (
        "Stabilization decreased by {delta}pp in the last {recent} days "
        "compared to the {baseline}-day baseline. "
        "This may indicate emerging iteration pressure or actively evolving subsystems."
    ),
    "trend_finding_stabilization_up": (
        "Stabilization improved by {delta}pp in the last {recent} days "
        "compared to the {baseline}-day baseline. "
        "This suggests delivery is becoming more durable."
    ),
    "trend_finding_churn_up": (
        "Churn rate increased by {delta}pp recently. "
        "This may reflect increased iteration on recent changes or evolving requirements."
    ),
    "trend_finding_churn_down": (
        "Churn rate decreased by {delta}pp recently. "
        "This suggests recent changes are stabilizing faster."
    ),
    "trend_finding_revert_up": (
        "Revert rate increased by {delta}pp recently. "
        "This may reflect integration challenges or deployment complexity in recent work."
    ),
    "trend_finding_intent_shift": (
        "{intent} shifted by {delta}pp ({direction}) in the recent window. "
        "This indicates a change in the dominant type of engineering activity."
    ),
    "trend_finding_pr_ttm_down": (
        "PR merge time improved by {delta}h recently, indicating faster integration flow."
    ),
    "trend_finding_pr_ttm_up": (
        "PR merge time increased by {delta}h recently. "
        "This may reflect larger PRs, more thorough review, or integration complexity."
    ),
    "trend_finding_pr_spr_down": (
        "PR single-pass rate decreased by {delta}pp recently. "
        "This may reflect evolving standards or increased review rigor."
    ),
    "trend_finding_pr_spr_up": (
        "PR single-pass rate improved by {delta}pp recently, "
        "suggesting code quality at submission is increasing."
    ),
    "trend_insufficient_data": (
        "Trend analysis requires at least 5 commits in the recent window "
        "(last {recent} days). This repository had {count} commits in the "
        "recent window. Trend data is not available."
    ),

    # --- Attention Signals (v0.4a) ---
    "attention_destabilizing": (
        "Recent activity shows destabilization: {description}."
    ),
    "attention_stabilizing": (
        "Recent activity shows improving stability: {description}."
    ),
    "attention_workflow_friction": (
        "PR lifecycle shows increased friction: {description}."
    ),
    "attention_composition_shift": (
        "Engineering activity composition shifted: {description}."
    ),
    "attention_stable": (
        "No significant changes detected between the recent window and baseline."
    ),
    "attention_mixed": (
        "Mixed signals: {positive} but {negative}."
    ),

    # Co-occurrence finding templates
    "cooccurrence_stability_cascade": (
        "Feature delivery is destabilizing ({feature_stab_delta}pp), "
        "driving churn increase ({churn_delta}pp) and reducing overall "
        "stabilization ({stab_delta}pp)."
    ),
    "cooccurrence_fix_instability": (
        "Corrective changes are not holding — Fix stabilization dropped "
        "{fix_stab_delta}pp while churn increased {churn_delta}pp."
    ),
    "cooccurrence_workflow_slowdown": (
        "PR lifecycle is slowing — merge time increased {ttm_delta}h "
        "and single-pass rate dropped {spr_delta}pp."
    ),
    "cooccurrence_recovery": (
        "Delivery is stabilizing — stabilization improved {stab_delta}pp "
        "with churn decreasing {churn_delta}pp."
    ),

    # --- AI Impact / Origin (v0.5) ---
    "section_ai_impact": "AI Impact on Code Durability",
    "table_origin": "Origin",
    "metric_origin_human": "Human",
    "metric_origin_ai_assisted": "AI-Assisted",
    "metric_origin_bot": "Bot",
    "org_ai_impact_title": "AI Impact Across Organization",
    "org_ai_impact_body": (
        "Of {total_repos} repositories, {ai_repos} contain AI-assisted commits. "
        "Median stabilization: Human {human_stab}, AI-Assisted {ai_stab}."
    ),

    # --- Adoption Timeline (SUN-191) ---
    "section_adoption_impact": "AI Adoption Impact",
    "adoption_header_clear": (
        "AI-assisted commits first appeared on {date}. "
        "Adoption reached steady state by {ramp_end}. "
        "{ai_count} AI-assisted commits detected."
    ),
    "adoption_header_sparse": (
        "AI-assisted commits first appeared on {date}. "
        "Usage remains sparse ({ai_count} total AI commits)."
    ),
    "adoption_pre_period": "Pre-adoption: {commits} commits over {days} days.",
    "adoption_post_period": "Post-adoption: {commits} commits over {days} days.",
    "table_pre_adoption": "Pre-Adoption",
    "table_post_adoption": "Post-Adoption",
    "cli_adoption_detected": "AI adoption detected ({confidence}), first AI commit on {date}.",
    "cli_adoption_insufficient": "AI adoption: insufficient data ({count} AI commits, need {min}).",
    "cli_adoption_no_pre": "AI adoption: not enough pre-adoption commits for comparison.",
    "cli_adoption_none": "No AI-assisted commits detected.",

    # --- Delivery Velocity (SUN-192) ---
    "section_delivery_velocity": "Delivery Velocity",
    "velocity_overall": (
        "Commit velocity: {cpw} commits/week, {lpw} lines/week."
    ),
    "velocity_trend_accelerating": "Velocity trend: accelerating ({change:+.0f}% over period).",
    "velocity_trend_decelerating": "Velocity trend: decelerating ({change:+.0f}% over period).",
    "velocity_trend_stable": "Velocity trend: stable ({change:+.0f}% over period).",
    "velocity_correlation_positive": (
        "Velocity-durability correlation: positive — "
        "faster delivery is associated with more stable code."
    ),
    "velocity_correlation_negative": (
        "Velocity-durability correlation: negative — "
        "faster delivery is associated with less stable code."
    ),
    "velocity_correlation_neutral": (
        "Velocity-durability correlation: neutral — "
        "no clear relationship between velocity and code stability."
    ),
    "velocity_correlation_caveat": (
        "Correlation does not imply causation. "
        "External factors may independently affect both velocity and stability."
    ),
    "cli_velocity_computed": (
        "Velocity: {cpw} commits/week ({trend})."
    ),
    "cli_velocity_skipped": "Velocity analysis skipped (< {min} commits).",

    # --- Fix Latency / Time to Rework (SUN-193) ---
    "section_fix_latency": "Code Durability — Time to Rework",
    "fix_latency_overall": (
        "Median time to rework: {median_days:.1f} days "
        "({fast} fast, {medium} medium, {slow} slow rework events)."
    ),
    "fix_latency_table_origin": "Origin",
    "fix_latency_table_median": "Median Rework",
    "fix_latency_table_fast_pct": "Fast (< 3d)",
    "fix_latency_table_events": "Events",
    "cli_fix_latency_computed": "Fix latency: median {median:.1f}h ({count} rework events).",
    "cli_fix_latency_none": "No rework events detected.",

    # --- Commit Shape (SUN-194) ---
    "section_commit_shape": "Commit Shape Analysis",
    "shape_overall": "Dominant commit shape: **{shape}** (median {files} files, {lpf:.0f} lines/file).",
    "shape_table_metric": "Metric",
    "shape_table_files": "Files/commit",
    "shape_table_lines": "Lines/file",
    "shape_table_spread": "Dir. spread",
    "shape_table_shape": "Shape",

    # --- AI Detection Coverage (SUN-158) ---
    "ai_coverage_high": (
        "AI detection coverage: {pct:.0f}% of commits have AI attribution."
    ),
    "ai_coverage_low": (
        "AI detection coverage: {pct:.0f}% of commits have AI attribution. "
        "If your team uses tools like Cursor, Windsurf, or Copilot inline, "
        "many AI-assisted commits may be classified as Human."
    ),
    "ai_coverage_none": (
        "No AI-assisted commits detected. If your team uses AI tools "
        "that don't add co-author tags (Cursor, Windsurf, Copilot inline), "
        "commits will appear as Human."
    ),

    # Org-level AI impact strings
    "org_ai_coverage_breakdown": (
        "Detection coverage: {high} repos with high coverage (>30%), "
        "{low} with low coverage (<30%), {none} with no AI detected."
    ),
    "org_ai_fix_latency_title": "Rework Speed by Origin (org-wide)",
    "org_ai_adoption_title": "AI Adoption Across Organization",
    "org_ai_adoption_body": (
        "{clear} repositories show clear AI adoption, "
        "{sparse} show sparse adoption, "
        "out of {total} repositories analyzed."
    ),

    # --- Org Report (v0.4b) ---
    "org_report_title": "DevXOS Organization Report",
    "org_label_organization": "Organization",
    "org_label_repos_analyzed": "Repositories analyzed",
    "org_label_recent_window": "Recent window",

    # Org report sections
    "org_section_what_changed": "What Changed Recently",
    "org_section_where_to_look": "Where to Look First",
    "org_section_delivery_trajectory": "Delivery Trajectory",
    "org_section_metrics_summary": "Organization Metrics Summary",
    "org_section_repo_overview": "Repository Overview",

    # Org metrics table
    "org_metric_total_commits": "Total commits",
    "org_metric_total_prs_merged": "Total PRs merged",
    "org_metric_repos_analyzed": "Repos analyzed",
    "org_metric_median_stabilization": "Median stabilization",
    "org_metric_median_revert_rate": "Median revert rate",

    # Org repo overview table
    "org_table_repository": "Repository",
    "org_table_commits": "Commits",
    "org_table_stabilization": "Stab.",
    "org_table_delta_stabilization": "Stab.",
    "org_table_prs": "PRs",
    "org_table_attention": "Attention",

    # CLI org messages
    "cli_help_org": "Path to organization directory containing Git repositories",
    "cli_help_repos": "Comma-separated list of repo names to analyze (default: all)",
    "cli_org_banner": "Organization",
    "cli_org_discovering": "Discovering repositories...",
    "cli_org_repos_found": "{count} repositories found.",
    "cli_org_no_repos": "No Git repositories found in the specified directory.",
    "cli_org_analyzing_repo": "Analyzing {repo}... ({current}/{total})",
    "cli_org_repo_done": "{repo}: {commits} commits, stabilization {stab}.",
    "cli_org_repo_skipped": "{repo}: skipped (no commits in window).",
    "cli_org_generating": "Generating organization report...",
    "cli_org_done": "Organization report complete.",
    "cli_org_label_report": "Org report",
    "cli_org_label_metrics": "Org metrics",
    "cli_error_org_not_dir": "Error: '{path}' is not a valid directory.",
    "cli_error_org_mutex": "Error: --org and repo_path are mutually exclusive.",

    # Org intelligence — change attribution
    "org_attribution_stability_dimension": (
        "stability (stabilization, churn)"
    ),
    "org_attribution_feature_dimension": (
        "feature delivery (feature stabilization, feature share)"
    ),
    "org_attribution_workflow_dimension": (
        "workflow dynamics (PR merge time, single-pass rate)"
    ),
    "org_attribution_composition_dimension": (
        "engineering composition (fix share, config share)"
    ),
    "org_attribution_intro": (
        "Across {repo_count} repositories with trend data, "
        "the most prominent pattern of change is associated with {dimension}, "
        "affecting {affected_count} repositories."
    ),
    "org_attribution_detail": (
        "In this period, {detail}."
    ),
    "org_attribution_none": (
        "No notable cross-repo patterns detected in the recent window."
    ),

    # Org intelligence — delivery narrative
    "org_narrative_intro": (
        "Of {total} repositories analyzed, "
        "{improving} show improving stabilization trajectories, "
        "{declining} show declining trajectories, "
        "and {stable} remain stable."
    ),
    "org_narrative_insufficient": (
        "{insufficient} repositories had insufficient data for trend analysis."
    ),
    "org_narrative_improving_dominant": (
        "The overall delivery trajectory is trending toward more durable outcomes, "
        "with the majority of active repositories showing stabilization improvements."
    ),
    "org_narrative_declining_dominant": (
        "The overall delivery trajectory shows increasing iteration pressure, "
        "with multiple repositories showing declining stabilization. "
        "This may coincide with active development phases or evolving requirements."
    ),
    "org_narrative_mixed": (
        "The delivery trajectory is mixed — some repositories are stabilizing "
        "while others show increased iteration. "
        "This is consistent with an organization where different teams "
        "are in different phases of their delivery cycle."
    ),
    "org_narrative_stable": (
        "The delivery trajectory is largely stable across the organization, "
        "with no significant shifts in stabilization patterns."
    ),
    "org_narrative_no_trend": (
        "Delivery trajectory analysis requires --trend flag with sufficient "
        "data in both baseline and recent windows."
    ),

    # Attention signal labels (for repo overview table)
    "org_attention_none": "stable",
    "org_attention_destabilizing": "destabilizing",
    "org_attention_stabilizing": "stabilizing",
    "org_attention_workflow_friction": "workflow friction",
    "org_attention_composition_shift": "composition shift",
    "org_attention_stable": "stable",
    "org_attention_mixed": "mixed",

    # --- Code Quality Insights (GitClear-inspired) ---

    # CLI status messages
    "cli_reading_diffs": "Reading diffs for code quality analysis...",
    "cli_diffs_analyzed": "{count} commit diffs analyzed.",
    "cli_duplicates_found": "Duplicates: {rate:.0%} rate ({count} blocks).",
    "cli_duplicates_none": "Duplicates: none detected.",
    "cli_moves_found": "Code movement: {pct:.1%} of changed lines moved between files.",
    "cli_moves_none": "Code movement: none detected.",
    "cli_provenance_done": "Provenance: {files} files blamed, {lines} lines sampled.",
    "cli_provenance_none": "Provenance: skipped (insufficient modification data).",
    "cli_new_churn_done": "New code churn: {rate_2w:.0%} (2w) / {rate_4w:.0%} (4w).",
    "cli_new_churn_none": "New code churn: skipped (insufficient data).",
    "cli_operations_done": "Operation mix: dominant = {dominant}.",
    "cli_operations_none": "Operation mix: skipped (insufficient data).",

    # Duplicate Code Detection section
    "section_duplicate_detection": "Duplicate Code Detection",
    "duplicate_summary": (
        "{rate:.0%} of analyzed commits contain duplicate code blocks "
        "({count} blocks detected, median size {median:.0f} lines)."
    ),
    "duplicate_table_origin": "Origin",
    "duplicate_table_commits": "Commits",
    "duplicate_table_rate": "Dup Rate",
    "duplicate_table_blocks": "Blocks",
    "duplicate_table_median": "Median Size",
    "finding_duplicate_high": (
        "Duplicate code block rate is {rate} — "
        "{count} identical blocks of 5+ lines were detected across files. "
        "This pattern is associated with copy-paste development and may "
        "indicate opportunities for consolidation."
    ),
    "systemic_duplicate_high": (
        "High duplication rates are commonly observed in codebases with "
        "AI-assisted development where context windows limit visibility "
        "of existing reusable code."
    ),
    "finding_duplicate_low": (
        "Duplicate code block rate is {rate}, "
        "indicating limited cross-file code repetition."
    ),

    # Code Movement / Refactoring Health section
    "section_moved_code": "Code Movement & Refactoring Health",
    "moved_summary": (
        "{pct:.1%} of changed lines were identified as moved between files."
    ),
    "moved_refactoring_ratio": "Refactoring ratio (moved / (moved + duplicated)): {ratio:.0%}.",
    "moved_table_origin": "Origin",
    "moved_table_commits": "Commits",
    "moved_table_with_moves": "With Moves",
    "moved_table_moved_lines": "Moved Lines",
    "moved_table_pct": "Moved %",
    "finding_moved_low": (
        "Only {pct} of changed lines represent code movement between files. "
        "Low code movement may indicate that refactoring and consolidation "
        "are not keeping pace with new code addition."
    ),
    "systemic_moved_low": (
        "Code movement is a signature of refactoring — developers extracting "
        "common logic into reusable modules. Its decline has been linked to "
        "increasing reliance on AI code generation."
    ),
    "finding_moved_healthy": (
        "{pct} of changed lines represent code movement between files, "
        "suggesting active refactoring and code consolidation."
    ),
    "finding_refactoring_ratio_low": (
        "Refactoring ratio is {ratio} — for every line of code moved to "
        "improve reuse, proportionally more lines are being duplicated."
    ),

    # Code Provenance section
    "section_code_provenance": "Code Provenance — Age of Revised Code",
    "provenance_summary": (
        "Among {lines} sampled lines across {files} files, "
        "the median age of code being revised is {median:.0f} days."
    ),
    "provenance_table_bracket": "Age Bracket",
    "provenance_table_pct": "% of Revisions",
    "provenance_bracket_under_2w": "< 2 weeks",
    "provenance_bracket_2_to_4w": "2-4 weeks",
    "provenance_bracket_1_to_12m": "1-12 months",
    "provenance_bracket_1_to_2y": "1-2 years",
    "provenance_bracket_over_2y": "2+ years",
    "provenance_table_origin": "Origin",
    "provenance_table_new_pct": "< 1 Month",
    "provenance_table_mature_pct": "> 1 Year",
    "provenance_table_median": "Median Age",
    "finding_provenance_new_heavy": (
        "{pct} of revised code is less than 1 month old. "
        "This suggests that recent code is being reworked at a high rate "
        "rather than maturing through the codebase."
    ),
    "systemic_provenance_new_heavy": (
        "When most revisions target recently-written code, it may indicate "
        "that initial implementations are incomplete or erroneous, requiring "
        "immediate correction rather than iterative improvement."
    ),
    "finding_provenance_balanced": (
        "{pct} of revised code is less than 1 month old — "
        "indicating a mix of recent iteration and mature code maintenance."
    ),

    # New Code Churn Rate section
    "section_new_code_churn": "New Code Churn Rate",
    "new_churn_summary": (
        "{rate_2w:.0%} of new-code files are re-modified within 2 weeks; "
        "{rate_4w:.0%} within 4 weeks."
    ),
    "new_churn_table_origin": "Origin",
    "new_churn_table_files": "New Code Files",
    "new_churn_table_2w": "Churned (2w)",
    "new_churn_table_4w": "Churned (4w)",
    "new_churn_table_rate_2w": "Rate (2w)",
    "new_churn_table_rate_4w": "Rate (4w)",
    "finding_new_churn_high": (
        "New code churn rate at 2 weeks is {rate} — "
        "a significant portion of newly added code requires revision "
        "shortly after introduction."
    ),
    "systemic_new_churn_high": (
        "High new-code churn rates suggest that initial implementations "
        "are frequently incomplete. This pattern has been observed to "
        "increase with AI-assisted development."
    ),
    "finding_new_churn_normal": (
        "New code churn rate at 2 weeks is {rate}, "
        "within typical range for iterative development."
    ),

    # Operation Mix section
    "section_operation_mix": "Operation Mix",
    "operation_summary": "Dominant operation: {dominant}.",
    "operation_table_origin": "Origin",
    "operation_table_added": "Added",
    "operation_table_deleted": "Deleted",
    "operation_table_updated": "Updated",
    "operation_table_moved": "Moved",
    "operation_table_duplicated": "Duplicated",
    "operation_table_dominant": "Dominant",
}


PT_BR = {
    # --- Relatório (writer.py) ---
    "report_title": "Relatório de Impacto de Engenharia DevXOS",
    "label_repository": "Repositório",
    "label_analysis_window": "Janela de análise",
    "label_churn_window": "Janela de churn",
    "unit_days": "dias",
    "section_metrics_summary": "Resumo de Métricas",
    "table_metric": "Métrica",
    "table_value": "Valor",
    "metric_commits_total": "Commits (total)",
    "metric_commits_revert": "Commits (reverts)",
    "metric_revert_rate": "Taxa de revert",
    "metric_churn_events": "Eventos de churn",
    "metric_churn_lines_affected": "Linhas afetadas por churn",
    "metric_files_touched": "Arquivos alterados",
    "metric_files_stabilized": "Arquivos estabilizados",
    "metric_stabilization_ratio": "Taxa de estabilização",
    "disclaimer": (
        "Relatório gerado por DevXOS v0.4b. "
        "As métricas são experimentais e devem ser tratadas como hipóteses, não conclusões."
    ),
    "system_disclaimer": (
        "Resultados de engenharia emergem de dinâmicas sistêmicas, complexidade do domínio "
        "e contexto organizacional. As métricas descrevem padrões observáveis e não devem "
        "ser interpretadas como avaliação de equipes ou indivíduos."
    ),

    # --- Nomes de zonas (relatórios de organização) ---
    "zone_stable": "Estável",
    "zone_transitional": "Transicional",
    "zone_volatile": "Volátil",
    "section_repos_by_stabilization": "Repositórios por Estabilização",

    # --- Intent / Comportamento (writer.py / narrative.py) ---
    "section_engineering_behavior": "Visão Geral do Comportamento de Engenharia",
    "section_stability_by_type": "Estabilidade por Tipo de Mudança",
    "table_intent": "Intenção",
    "table_commits": "Commits",
    "table_percentage": "%",
    "table_lines_changed": "Linhas Alteradas",
    "table_files_touched": "Arquivos",
    "table_stabilization": "Estabilização",
    "table_churn_events": "Eventos de Churn",
    "metric_intent_feature": "Feature",
    "metric_intent_fix": "Fix",
    "metric_intent_refactor": "Refactor",
    "metric_intent_config": "Config",
    "metric_intent_unknown": "Desconhecido",

    # --- Ciclo de Vida de PRs (writer.py / narrative.py) ---
    "section_pr_lifecycle": "Ciclo de Vida de PRs",
    "metric_pr_merged_count": "PRs merged",
    "metric_pr_median_time_to_merge": "Mediana de tempo para merge (horas)",
    "metric_pr_median_size_files": "Mediana de tamanho do PR (arquivos)",
    "metric_pr_median_size_lines": "Mediana de tamanho do PR (linhas)",
    "metric_pr_review_rounds_median": "Mediana de rodadas de revisão",
    "metric_pr_single_pass_rate": "Taxa de aprovação direta",

    # --- Explicações sistêmicas (narrative.py) ---
    "systemic_stabilization_low": (
        "Isso pode refletir complexidade do domínio, requisitos em evolução "
        "ou subsistemas em desenvolvimento ativo."
    ),
    "systemic_revert_high": (
        "Isso pode refletir complexidade de integração, desafios de deploy "
        "ou ciclos de experimentação rápidos."
    ),
    "systemic_churn_high": (
        "Isso pode refletir desenvolvimento iterativo, requisitos em evolução "
        "ou áreas do sistema em aprendizado ativo."
    ),
    "systemic_intent_dominant_feature": (
        "Isso pode indicar uma fase de expansão ou investimento em novas funcionalidades."
    ),
    "systemic_intent_dominant_fix": (
        "Isso pode indicar uma fase de estabilização, remediação de débito técnico "
        "ou refinamento pós-lançamento."
    ),
    "systemic_intent_dominant_config": (
        "Isso pode indicar investimento em maturidade operacional ou pipelines "
        "de deploy complexos requerendo ajuste iterativo."
    ),
    "systemic_intent_dominant_refactor": (
        "Isso pode indicar investimento estrutural para manutenibilidade de longo prazo."
    ),
    "systemic_intent_dominant_unknown": (
        "Adotar mensagens de commit convencionais melhoraria a precisão da classificação."
    ),
    "systemic_intent_fix_churn_high": (
        "Isso pode refletir domínios complexos onde trabalho corretivo "
        "requer múltiplas iterações para convergir."
    ),
    "systemic_intent_stabilization_gap": (
        "Diferentes tipos de mudança naturalmente estabilizam em velocidades diferentes "
        "dependendo da complexidade do domínio e ciclos de feedback."
    ),
    "systemic_pr_single_pass_low": (
        "Isso pode refletir rigor saudável de revisão, mudanças complexas "
        "que requerem discussão ou padrões de código em evolução."
    ),

    # --- Narrativa (narrative.py) ---
    "section_key_findings": "Principais Descobertas",
    "section_metric_details": "Detalhes das Métricas",

    # Templates de descobertas-chave
    "finding_stabilization_low": (
        "A taxa de estabilização é {ratio} — "
        "{unstable_pct} dos arquivos modificados foram alterados novamente dentro "
        "da janela de churn. Isso pode indicar esforço corretivo significativo."
    ),
    "finding_stabilization_high": (
        "A taxa de estabilização é {ratio} — "
        "a maioria das alterações persistiu sem modificação posterior. "
        "Isso sugere entrega durável."
    ),
    "finding_revert_high": (
        "A taxa de revert é {rate} "
        "({reverts} de {total} commits). "
        "Isso está acima do limiar de {threshold} e pode "
        "indicar instabilidade crescente."
    ),
    "finding_revert_low": (
        "A taxa de revert é {rate} "
        "({reverts} de {total} commits), "
        "dentro de uma faixa saudável."
    ),
    "finding_churn_high": (
        "{events} arquivos apresentaram churn ({ratio} dos "
        "arquivos alterados), afetando {lines} linhas. "
        "Churn elevado pode indicar que as alterações não estão estabilizando."
    ),
    "finding_churn_low": (
        "{events} arquivos apresentaram churn ({ratio} dos "
        "arquivos alterados), afetando {lines} linhas."
    ),
    "finding_volume": (
        "{commits} commits analisados em "
        "{files} arquivos únicos."
    ),

    # Descobertas de PR
    "finding_pr_volume": (
        "{count} PRs merged neste período com "
        "mediana de tempo para merge de {hours} horas."
    ),
    "finding_pr_single_pass_high": (
        "{rate} dos PRs foram merged sem nenhuma solicitação de alteração "
        "(taxa de aprovação direta), sugerindo ciclos de revisão eficientes."
    ),
    "finding_pr_single_pass_low": (
        "Apenas {rate} dos PRs foram merged sem solicitações de alteração. "
        "A maioria dos PRs exigiu pelo menos uma rodada de revisão."
    ),

    # Explicações de métricas de PR
    "explain_pr_time_to_merge_title": "Mediana de Tempo para Merge",
    "explain_pr_time_to_merge_body": (
        "O pull request mediano levou {hours} horas da abertura ao merge, "
        "entre {count} PRs merged. Isso mede a velocidade do ciclo de feedback — "
        "tempos menores podem indicar ciclos de revisão mais suaves ou PRs menores."
    ),
    "explain_pr_single_pass_title": "Taxa de Aprovação Direta",
    "explain_pr_single_pass_body": (
        "{rate} dos PRs foram merged sem nenhum review de CHANGES_REQUESTED. "
        "O PR mediano passou por {rounds} rodadas de revisão. "
        "Uma taxa alta de aprovação direta pode indicar que o código é bem preparado antes da revisão, "
        "potencialmente auxiliado por desenvolvimento assistido por IA."
    ),

    # Descobertas de intent
    "finding_intent_dominant": (
        "Commits de {intent} dominam com {pct}, "
        "sugerindo que a principal atividade de engenharia é {interpretation}."
    ),
    "finding_intent_fix_churn_high": (
        "Mudanças de Fix apresentam {fix_churn} eventos de churn, "
        "{comparison} o churn de Feature ({feat_churn} eventos). "
        "Isso sugere que trabalho corretivo é uma fonte significativa de instabilidade."
    ),
    "finding_intent_fix_churn_low": (
        "Mudanças de Fix apresentam {fix_churn} eventos de churn, "
        "comparável ao churn de Feature ({feat_churn} eventos)."
    ),
    "finding_intent_stabilization_gap": (
        "A estabilização varia por intenção: {best} com {best_ratio} "
        "vs {worst} com {worst_ratio}."
    ),
    "intent_interpretation_feature": "desenvolvimento de novas funcionalidades",
    "intent_interpretation_fix": "trabalho corretivo e de remediação",
    "intent_interpretation_refactor": "melhoria estrutural",
    "intent_interpretation_config": "configuração e infraestrutura",
    "intent_interpretation_unknown": "atividade não classificada",

    # Explicações de métricas de intent
    "explain_intent_distribution_title": "Comportamento de Engenharia",
    "explain_intent_distribution_body": (
        "Commits foram classificados por intenção: "
        "{feature} Feature, {fix} Fix, {refactor} Refactor, "
        "{config} Config, {unknown} Unknown. "
        "Essa distribuição revela o tipo dominante de atividade de engenharia — "
        "se o time está construindo, corrigindo ou reestruturando."
    ),
    "explain_intent_stability_title": "Estabilidade por Intenção",
    "explain_intent_stability_body": (
        "Taxa de estabilização por tipo de mudança: "
        "Feature {feat_ratio}, Fix {fix_ratio}, Refactor {refactor_ratio}. "
        "Comparar a estabilidade entre intenções revela quais tipos de mudanças "
        "produzem resultados duráveis e quais requerem iteração adicional."
    ),

    # CLI
    "cli_reading_prs": "Buscando pull requests...",
    "cli_prs_found": "{count} PRs merged encontrados.",
    "cli_prs_skipped": "pulado (sem remote GitHub ou gh CLI).",
    "cli_classifying": "Classificando commits...",
    "cli_classified": "{count} commits classificados.",

    # Explicações das métricas
    "explain_revert_rate_title": "Taxa de Revert",
    "explain_revert_rate_body": (
        "{reverts} de {total} commits neste período "
        "foram identificados como reverts (commits que desfazem trabalho anterior). "
        "A taxa de revert é um indicador de instabilidade — mede com que frequência "
        "as alterações precisam ser completamente revertidas. A detecção é baseada em "
        "padrões de mensagem de commit e pode não capturar todos os reverts manuais."
    ),
    "explain_churn_events_title": "Eventos de Churn",
    "explain_churn_events_body": (
        "Um evento de churn ocorre quando um arquivo é modificado múltiplas vezes dentro "
        "da janela de churn. {events} arquivos foram modificados repetidamente, "
        "envolvendo {lines} linhas alteradas no total. "
        "Churn elevado pode indicar esforço corretivo — código sendo corrigido ou "
        "reescrito logo após a entrega inicial."
    ),
    "explain_stabilization_title": "Taxa de Estabilização",
    "explain_stabilization_body": (
        "{stabilized} de {touched} arquivos não foram "
        "modificados novamente dentro da janela de churn após sua última alteração. "
        "Este é o indicador central de sinal/ruído: uma taxa alta significa que as "
        "alterações persistem (sinal de entrega), uma taxa baixa significa que as "
        "alterações são frequentemente reescritas (ruído de engenharia)."
    ),

    # --- CLI (cli.py) ---
    "cli_description": (
        "Inteligência de engenharia para a era da IA. "
        "Analisa um repositório Git e gera um relatório de impacto "
        "medindo sinal de entrega vs ruído."
    ),
    "cli_help_repo": "Caminho para um repositório Git local",
    "cli_help_days": "Janela de análise em dias (padrão: 90)",
    "cli_help_churn_days": "Janela de detecção de churn em dias (padrão: 14)",
    "cli_help_out": "Diretório de saída (padrão: out)",
    "cli_help_lang": "Idioma do relatório: en, pt-br (padrão: en)",
    "cli_error_not_dir": "Erro: '{path}' não é um diretório válido.",
    "cli_error_not_git": "Erro: '{path}' não é um repositório Git.",
    "cli_banner_repo": "Repositório",
    "cli_banner_lookback": "Análise",
    "cli_banner_churn": "Janela de churn",
    "cli_banner_output": "Diretório",
    "cli_reading_commits": "Lendo histórico de commits...",
    "cli_commits_found": "{count} commits encontrados.",
    "cli_no_commits": "Nenhum commit encontrado na janela especificada. Nada a analisar.",
    "cli_analyzing": "Analisando...",
    "cli_done": "pronto.",
    "cli_writing_report": "Escrevendo relatório...",
    "cli_label_report": "Relatório",
    "cli_label_metrics": "Métricas",

    # --- Análise de Tendência (v0.3) ---
    "cli_help_trend": "Habilitar análise de tendência (compara recente vs baseline)",
    "cli_help_recent_days": "Janela recente em dias para análise de tendência (padrão: 30)",
    "cli_trend_analyzing": "Computando análise de tendência...",
    "cli_trend_done": "Tendência {recent}d vs {baseline}d computada.",
    "cli_trend_insufficient": "Tendência pulada (apenas {count} commits na janela recente, necessário ≥5).",

    "section_trend_analysis": "Análise de Tendência (últimos {recent} dias vs baseline de {baseline} dias)",
    "table_baseline": "Baseline",
    "table_recent": "Recente",
    "table_delta": "Delta",
    "table_signal": "Sinal",

    "trend_signal_stable": "— Estável",
    "trend_signal_notable_up": "▲ Notável",
    "trend_signal_notable_down": "▼ Notável",
    "trend_signal_significant_up": "▲ Significativo",
    "trend_signal_significant_down": "▼ Significativo",

    "trend_label_stabilization": "Estabilização",
    "trend_label_churn_rate": "Taxa de churn",
    "trend_label_revert_rate": "Taxa de revert",
    "trend_label_feature_share": "Participação Feature",
    "trend_label_fix_share": "Participação Fix",
    "trend_label_config_share": "Participação Config",
    "trend_label_feature_stabilization": "Estabilização Feature",
    "trend_label_fix_stabilization": "Estabilização Fix",
    "trend_label_pr_time_to_merge": "Tempo de merge de PR",
    "trend_label_pr_single_pass": "Taxa de aprovação direta",

    "trend_finding_stabilization_down": (
        "A estabilização diminuiu {delta}pp nos últimos {recent} dias "
        "comparado à baseline de {baseline} dias. "
        "Isso pode indicar pressão de iteração emergente ou subsistemas em evolução ativa."
    ),
    "trend_finding_stabilization_up": (
        "A estabilização melhorou {delta}pp nos últimos {recent} dias "
        "comparado à baseline de {baseline} dias. "
        "Isso sugere que a entrega está se tornando mais durável."
    ),
    "trend_finding_churn_up": (
        "A taxa de churn aumentou {delta}pp recentemente. "
        "Isso pode refletir maior iteração em mudanças recentes ou requisitos em evolução."
    ),
    "trend_finding_churn_down": (
        "A taxa de churn diminuiu {delta}pp recentemente. "
        "Isso sugere que mudanças recentes estão estabilizando mais rápido."
    ),
    "trend_finding_revert_up": (
        "A taxa de revert aumentou {delta}pp recentemente. "
        "Isso pode refletir desafios de integração ou complexidade de deploy no trabalho recente."
    ),
    "trend_finding_intent_shift": (
        "{intent} mudou {delta}pp ({direction}) na janela recente. "
        "Isso indica uma mudança no tipo dominante de atividade de engenharia."
    ),
    "trend_finding_pr_ttm_down": (
        "O tempo de merge de PR melhorou {delta}h recentemente, indicando fluxo de integração mais rápido."
    ),
    "trend_finding_pr_ttm_up": (
        "O tempo de merge de PR aumentou {delta}h recentemente. "
        "Isso pode refletir PRs maiores, revisão mais detalhada ou complexidade de integração."
    ),
    "trend_finding_pr_spr_down": (
        "A taxa de aprovação direta diminuiu {delta}pp recentemente. "
        "Isso pode refletir padrões em evolução ou maior rigor de revisão."
    ),
    "trend_finding_pr_spr_up": (
        "A taxa de aprovação direta melhorou {delta}pp recentemente, "
        "sugerindo que a qualidade do código na submissão está aumentando."
    ),
    "trend_insufficient_data": (
        "A análise de tendência requer pelo menos 5 commits na janela recente "
        "(últimos {recent} dias). Este repositório teve {count} commits na "
        "janela recente. Dados de tendência não estão disponíveis."
    ),

    # --- Sinais de Atenção (v0.4a) ---
    "attention_destabilizing": (
        "Atividade recente mostra desestabilização: {description}."
    ),
    "attention_stabilizing": (
        "Atividade recente mostra melhoria de estabilidade: {description}."
    ),
    "attention_workflow_friction": (
        "Ciclo de vida de PR mostra fricção crescente: {description}."
    ),
    "attention_composition_shift": (
        "Composição da atividade de engenharia mudou: {description}."
    ),
    "attention_stable": (
        "Nenhuma mudança significativa detectada entre a janela recente e o baseline."
    ),
    "attention_mixed": (
        "Sinais mistos: {positive} mas {negative}."
    ),

    # Templates de co-ocorrência
    "cooccurrence_stability_cascade": (
        "Entrega de Features está desestabilizando ({feature_stab_delta}pp), "
        "gerando aumento de churn ({churn_delta}pp) e reduzindo estabilização "
        "geral ({stab_delta}pp)."
    ),
    "cooccurrence_fix_instability": (
        "Mudanças corretivas não estão persistindo — estabilização de Fix caiu "
        "{fix_stab_delta}pp enquanto churn aumentou {churn_delta}pp."
    ),
    "cooccurrence_workflow_slowdown": (
        "Ciclo de vida de PR está desacelerando — tempo de merge aumentou "
        "{ttm_delta}h e taxa de aprovação direta caiu {spr_delta}pp."
    ),
    "cooccurrence_recovery": (
        "Entrega está estabilizando — estabilização melhorou {stab_delta}pp "
        "com churn diminuindo {churn_delta}pp."
    ),

    # --- AI Impact / Origem (v0.5) ---
    "section_ai_impact": "Impacto de IA na Durabilidade do Código",
    "table_origin": "Origem",
    "metric_origin_human": "Humano",
    "metric_origin_ai_assisted": "Assistido por IA",
    "metric_origin_bot": "Bot",
    "org_ai_impact_title": "Impacto de IA na Organização",
    "org_ai_impact_body": (
        "De {total_repos} repositórios, {ai_repos} contêm commits assistidos por IA. "
        "Mediana de estabilização: Humano {human_stab}, Assistido por IA {ai_stab}."
    ),

    # --- Timeline de Adoção (SUN-191) ---
    "section_adoption_impact": "Impacto da Adoção de IA",
    "adoption_header_clear": (
        "Commits assistidos por IA apareceram pela primeira vez em {date}. "
        "Adoção atingiu estado estável em {ramp_end}. "
        "{ai_count} commits assistidos por IA detectados."
    ),
    "adoption_header_sparse": (
        "Commits assistidos por IA apareceram pela primeira vez em {date}. "
        "Uso permanece esparso ({ai_count} commits de IA no total)."
    ),
    "adoption_pre_period": "Pré-adoção: {commits} commits em {days} dias.",
    "adoption_post_period": "Pós-adoção: {commits} commits em {days} dias.",
    "table_pre_adoption": "Pré-Adoção",
    "table_post_adoption": "Pós-Adoção",
    "cli_adoption_detected": "Adoção de IA detectada ({confidence}), primeiro commit IA em {date}.",
    "cli_adoption_insufficient": "Adoção de IA: dados insuficientes ({count} commits IA, necessário {min}).",
    "cli_adoption_no_pre": "Adoção de IA: commits pré-adoção insuficientes para comparação.",
    "cli_adoption_none": "Nenhum commit assistido por IA detectado.",

    # --- Velocidade de Entrega (SUN-192) ---
    "section_delivery_velocity": "Velocidade de Entrega",
    "velocity_overall": (
        "Velocidade de commits: {cpw} commits/semana, {lpw} linhas/semana."
    ),
    "velocity_trend_accelerating": "Tendência de velocidade: acelerando ({change:+.0f}% no período).",
    "velocity_trend_decelerating": "Tendência de velocidade: desacelerando ({change:+.0f}% no período).",
    "velocity_trend_stable": "Tendência de velocidade: estável ({change:+.0f}% no período).",
    "velocity_correlation_positive": (
        "Correlação velocidade-durabilidade: positiva — "
        "entrega mais rápida está associada a código mais estável."
    ),
    "velocity_correlation_negative": (
        "Correlação velocidade-durabilidade: negativa — "
        "entrega mais rápida está associada a código menos estável."
    ),
    "velocity_correlation_neutral": (
        "Correlação velocidade-durabilidade: neutra — "
        "sem relação clara entre velocidade e estabilidade do código."
    ),
    "velocity_correlation_caveat": (
        "Correlação não implica causalidade. "
        "Fatores externos podem afetar velocidade e estabilidade independentemente."
    ),
    "cli_velocity_computed": (
        "Velocidade: {cpw} commits/semana ({trend})."
    ),
    "cli_velocity_skipped": "Análise de velocidade pulada (< {min} commits).",

    # --- Fix Latency / Tempo de Retrabalho (SUN-193) ---
    "section_fix_latency": "Durabilidade do Código — Tempo de Retrabalho",
    "fix_latency_overall": (
        "Mediana de tempo para retrabalho: {median_days:.1f} dias "
        "({fast} rápido, {medium} médio, {slow} lento)."
    ),
    "fix_latency_table_origin": "Origem",
    "fix_latency_table_median": "Mediana Retrabalho",
    "fix_latency_table_fast_pct": "Rápido (< 3d)",
    "fix_latency_table_events": "Eventos",
    "cli_fix_latency_computed": "Latência de fix: mediana {median:.1f}h ({count} eventos de retrabalho).",
    "cli_fix_latency_none": "Nenhum evento de retrabalho detectado.",

    # --- Formato de Commit (SUN-194) ---
    "section_commit_shape": "Análise de Formato de Commit",
    "shape_overall": "Formato dominante: **{shape}** (mediana {files} arquivos, {lpf:.0f} linhas/arquivo).",
    "shape_table_metric": "Métrica",
    "shape_table_files": "Arquivos/commit",
    "shape_table_lines": "Linhas/arquivo",
    "shape_table_spread": "Spread dir.",
    "shape_table_shape": "Formato",

    # --- Cobertura de Detecção AI (SUN-158) ---
    "ai_coverage_high": (
        "Cobertura de detecção AI: {pct:.0f}% dos commits possuem atribuição AI."
    ),
    "ai_coverage_low": (
        "Cobertura de detecção AI: {pct:.0f}% dos commits possuem atribuição AI. "
        "Se sua equipe usa ferramentas como Cursor, Windsurf ou Copilot inline, "
        "muitos commits assistidos por AI podem estar classificados como Humano."
    ),
    "ai_coverage_none": (
        "Nenhum commit assistido por AI detectado. Se sua equipe usa ferramentas AI "
        "que não adicionam co-author tags (Cursor, Windsurf, Copilot inline), "
        "os commits aparecerão como Humano."
    ),

    # Strings org-level AI impact
    "org_ai_coverage_breakdown": (
        "Cobertura de detecção: {high} repos com alta cobertura (>30%), "
        "{low} com baixa cobertura (<30%), {none} sem AI detectada."
    ),
    "org_ai_fix_latency_title": "Velocidade de Retrabalho por Origem (org-wide)",
    "org_ai_adoption_title": "Adoção de AI na Organização",
    "org_ai_adoption_body": (
        "{clear} repositórios mostram adoção clara de AI, "
        "{sparse} mostram adoção esparsa, "
        "de {total} repositórios analisados."
    ),

    # --- Relatório Org (v0.4b) ---
    "org_report_title": "Relatório Organizacional DevXOS",
    "org_label_organization": "Organização",
    "org_label_repos_analyzed": "Repositórios analisados",
    "org_label_recent_window": "Janela recente",

    # Seções do relatório org
    "org_section_what_changed": "O que Mudou Recentemente",
    "org_section_where_to_look": "Onde Olhar Primeiro",
    "org_section_delivery_trajectory": "Trajetória de Entrega",
    "org_section_metrics_summary": "Resumo de Métricas da Organização",
    "org_section_repo_overview": "Visão Geral dos Repositórios",

    # Tabela de métricas org
    "org_metric_total_commits": "Total de commits",
    "org_metric_total_prs_merged": "Total de PRs merged",
    "org_metric_repos_analyzed": "Repositórios analisados",
    "org_metric_median_stabilization": "Mediana de estabilização",
    "org_metric_median_revert_rate": "Mediana de taxa de revert",

    # Tabela de visão geral dos repos
    "org_table_repository": "Repositório",
    "org_table_commits": "Commits",
    "org_table_stabilization": "Estab.",
    "org_table_delta_stabilization": "Estab.",
    "org_table_prs": "PRs",
    "org_table_attention": "Atenção",

    # CLI mensagens org
    "cli_help_org": "Caminho para o diretório da organização contendo repositórios Git",
    "cli_help_repos": "Lista de nomes de repos separados por vírgula (padrão: todos)",
    "cli_org_banner": "Organização",
    "cli_org_discovering": "Descobrindo repositórios...",
    "cli_org_repos_found": "{count} repositórios encontrados.",
    "cli_org_no_repos": "Nenhum repositório Git encontrado no diretório especificado.",
    "cli_org_analyzing_repo": "Analisando {repo}... ({current}/{total})",
    "cli_org_repo_done": "{repo}: {commits} commits, estabilização {stab}.",
    "cli_org_repo_skipped": "{repo}: pulado (sem commits na janela).",
    "cli_org_generating": "Gerando relatório organizacional...",
    "cli_org_done": "Relatório organizacional completo.",
    "cli_org_label_report": "Relatório org",
    "cli_org_label_metrics": "Métricas org",
    "cli_error_org_not_dir": "Erro: '{path}' não é um diretório válido.",
    "cli_error_org_mutex": "Erro: --org e repo_path são mutuamente exclusivos.",

    # Org inteligência — atribuição de mudança
    "org_attribution_stability_dimension": (
        "estabilidade (estabilização, churn)"
    ),
    "org_attribution_feature_dimension": (
        "entrega de features (estabilização de feature, participação de feature)"
    ),
    "org_attribution_workflow_dimension": (
        "dinâmicas de workflow (tempo de merge de PR, taxa de aprovação direta)"
    ),
    "org_attribution_composition_dimension": (
        "composição de engenharia (participação de fix, participação de config)"
    ),
    "org_attribution_intro": (
        "Nos {repo_count} repositórios com dados de tendência, "
        "o padrão de mudança mais proeminente está associado a {dimension}, "
        "afetando {affected_count} repositórios."
    ),
    "org_attribution_detail": (
        "Neste período, {detail}."
    ),
    "org_attribution_none": (
        "Nenhum padrão cross-repo notável detectado na janela recente."
    ),

    # Org inteligência — narrativa de entrega
    "org_narrative_intro": (
        "Dos {total} repositórios analisados, "
        "{improving} mostram trajetórias de estabilização melhorando, "
        "{declining} mostram trajetórias declinando, "
        "e {stable} permanecem estáveis."
    ),
    "org_narrative_insufficient": (
        "{insufficient} repositórios tiveram dados insuficientes para análise de tendência."
    ),
    "org_narrative_improving_dominant": (
        "A trajetória geral de entrega tende a resultados mais duráveis, "
        "com a maioria dos repositórios ativos mostrando melhorias de estabilização."
    ),
    "org_narrative_declining_dominant": (
        "A trajetória geral de entrega mostra pressão de iteração crescente, "
        "com múltiplos repositórios mostrando estabilização declinante. "
        "Isso pode coincidir com fases de desenvolvimento ativo ou requisitos em evolução."
    ),
    "org_narrative_mixed": (
        "A trajetória de entrega é mista — alguns repositórios estão estabilizando "
        "enquanto outros mostram iteração crescente. "
        "Isso é consistente com uma organização onde diferentes equipes "
        "estão em diferentes fases de seus ciclos de entrega."
    ),
    "org_narrative_stable": (
        "A trajetória de entrega é amplamente estável em toda a organização, "
        "sem mudanças significativas nos padrões de estabilização."
    ),
    "org_narrative_no_trend": (
        "A análise de trajetória de entrega requer a flag --trend com dados "
        "suficientes nas janelas baseline e recente."
    ),

    # Labels de sinais de atenção (para tabela de repositórios)
    "org_attention_none": "estável",
    "org_attention_destabilizing": "desestabilizando",
    "org_attention_stabilizing": "estabilizando",
    "org_attention_workflow_friction": "fricção no workflow",
    "org_attention_composition_shift": "mudança de composição",
    "org_attention_stable": "estável",
    "org_attention_mixed": "misto",

    # --- Insights de Qualidade de Código (inspirado GitClear) ---

    # Mensagens CLI
    "cli_reading_diffs": "Lendo diffs para análise de qualidade de código...",
    "cli_diffs_analyzed": "{count} diffs de commits analisados.",
    "cli_duplicates_found": "Duplicação: {rate:.0%} taxa ({count} blocos).",
    "cli_duplicates_none": "Duplicação: nenhuma detectada.",
    "cli_moves_found": "Movimentação: {pct:.1%} das linhas alteradas movidas entre arquivos.",
    "cli_moves_none": "Movimentação: nenhuma detectada.",
    "cli_provenance_done": "Proveniência: {files} arquivos analisados, {lines} linhas amostradas.",
    "cli_provenance_none": "Proveniência: ignorado (dados de modificação insuficientes).",
    "cli_new_churn_done": "Churn de código novo: {rate_2w:.0%} (2s) / {rate_4w:.0%} (4s).",
    "cli_new_churn_none": "Churn de código novo: ignorado (dados insuficientes).",
    "cli_operations_done": "Mix de operações: dominante = {dominant}.",
    "cli_operations_none": "Mix de operações: ignorado (dados insuficientes).",

    # Seção Detecção de Código Duplicado
    "section_duplicate_detection": "Detecção de Código Duplicado",
    "duplicate_summary": (
        "{rate:.0%} dos commits analisados contêm blocos de código duplicado "
        "({count} blocos detectados, tamanho mediano {median:.0f} linhas)."
    ),
    "duplicate_table_origin": "Origem",
    "duplicate_table_commits": "Commits",
    "duplicate_table_rate": "Taxa Dup",
    "duplicate_table_blocks": "Blocos",
    "duplicate_table_median": "Tamanho Mediano",
    "finding_duplicate_high": (
        "Taxa de blocos duplicados é {rate} — "
        "{count} blocos idênticos de 5+ linhas foram detectados entre arquivos. "
        "Esse padrão está associado a desenvolvimento copy-paste e pode "
        "indicar oportunidades de consolidação."
    ),
    "systemic_duplicate_high": (
        "Altas taxas de duplicação são comumente observadas em codebases com "
        "desenvolvimento assistido por IA, onde janelas de contexto limitam "
        "a visibilidade de código reutilizável existente."
    ),
    "finding_duplicate_low": (
        "Taxa de blocos duplicados é {rate}, "
        "indicando repetição limitada de código entre arquivos."
    ),

    # Seção Movimentação de Código / Saúde de Refatoração
    "section_moved_code": "Movimentação de Código & Saúde de Refatoração",
    "moved_summary": (
        "{pct:.1%} das linhas alteradas foram identificadas como movidas entre arquivos."
    ),
    "moved_refactoring_ratio": "Razão de refatoração (movido / (movido + duplicado)): {ratio:.0%}.",
    "moved_table_origin": "Origem",
    "moved_table_commits": "Commits",
    "moved_table_with_moves": "Com Movimentação",
    "moved_table_moved_lines": "Linhas Movidas",
    "moved_table_pct": "% Movido",
    "finding_moved_low": (
        "Apenas {pct} das linhas alteradas representam movimentação de código. "
        "Baixa movimentação pode indicar que refatoração e consolidação "
        "não estão acompanhando a adição de código novo."
    ),
    "systemic_moved_low": (
        "Movimentação de código é a assinatura de refatoração — desenvolvedores "
        "extraindo lógica comum em módulos reutilizáveis. Seu declínio tem sido "
        "associado ao aumento da dependência de geração de código por IA."
    ),
    "finding_moved_healthy": (
        "{pct} das linhas alteradas representam movimentação entre arquivos, "
        "sugerindo refatoração ativa e consolidação de código."
    ),
    "finding_refactoring_ratio_low": (
        "Razão de refatoração é {ratio} — para cada linha movida para "
        "melhorar reuso, proporcionalmente mais linhas estão sendo duplicadas."
    ),

    # Seção Proveniência de Código
    "section_code_provenance": "Proveniência de Código — Idade do Código Revisado",
    "provenance_summary": (
        "Entre {lines} linhas amostradas em {files} arquivos, "
        "a idade mediana do código sendo revisado é {median:.0f} dias."
    ),
    "provenance_table_bracket": "Faixa de Idade",
    "provenance_table_pct": "% das Revisões",
    "provenance_bracket_under_2w": "< 2 semanas",
    "provenance_bracket_2_to_4w": "2-4 semanas",
    "provenance_bracket_1_to_12m": "1-12 meses",
    "provenance_bracket_1_to_2y": "1-2 anos",
    "provenance_bracket_over_2y": "2+ anos",
    "provenance_table_origin": "Origem",
    "provenance_table_new_pct": "< 1 Mês",
    "provenance_table_mature_pct": "> 1 Ano",
    "provenance_table_median": "Idade Mediana",
    "finding_provenance_new_heavy": (
        "{pct} do código revisado tem menos de 1 mês. "
        "Isso sugere que código recente está sendo retrabalhado em alta taxa "
        "em vez de amadurecer na codebase."
    ),
    "systemic_provenance_new_heavy": (
        "Quando a maioria das revisões é sobre código recente, pode indicar "
        "que implementações iniciais estão incompletas ou incorretas, "
        "exigindo correção imediata em vez de melhoria iterativa."
    ),
    "finding_provenance_balanced": (
        "{pct} do código revisado tem menos de 1 mês — "
        "indicando um equilíbrio entre iteração recente e manutenção de código maduro."
    ),

    # Seção Taxa de Churn de Código Novo
    "section_new_code_churn": "Taxa de Churn de Código Novo",
    "new_churn_summary": (
        "{rate_2w:.0%} dos arquivos com código novo são remodificados em 2 semanas; "
        "{rate_4w:.0%} em 4 semanas."
    ),
    "new_churn_table_origin": "Origem",
    "new_churn_table_files": "Arquivos com Código Novo",
    "new_churn_table_2w": "Churned (2s)",
    "new_churn_table_4w": "Churned (4s)",
    "new_churn_table_rate_2w": "Taxa (2s)",
    "new_churn_table_rate_4w": "Taxa (4s)",
    "finding_new_churn_high": (
        "Taxa de churn de código novo em 2 semanas é {rate} — "
        "uma porção significativa do código recém-adicionado requer revisão "
        "logo após a introdução."
    ),
    "systemic_new_churn_high": (
        "Altas taxas de churn de código novo sugerem que implementações "
        "iniciais são frequentemente incompletas. Esse padrão tem sido "
        "observado com maior frequência em desenvolvimento assistido por IA."
    ),
    "finding_new_churn_normal": (
        "Taxa de churn de código novo em 2 semanas é {rate}, "
        "dentro da faixa típica para desenvolvimento iterativo."
    ),

    # Seção Mix de Operações
    "section_operation_mix": "Mix de Operações",
    "operation_summary": "Operação dominante: {dominant}.",
    "operation_table_origin": "Origem",
    "operation_table_added": "Adicionado",
    "operation_table_deleted": "Deletado",
    "operation_table_updated": "Atualizado",
    "operation_table_moved": "Movido",
    "operation_table_duplicated": "Duplicado",
    "operation_table_dominant": "Dominante",
}


_LANGUAGES = {
    "en": EN,
    "pt-br": PT_BR,
}

SUPPORTED_LANGS = list(_LANGUAGES.keys())


def get_strings(lang: str = "en") -> dict[str, str]:
    """Return the string dictionary for the given language code.

    Falls back to English if the language is not supported.
    """
    return _LANGUAGES.get(lang, EN)
